### PR TITLE
plus_html_and_scss

### PR DESCRIPTION
**Pull request by chaochaowu**
WIP: after add user_define model, user_define#edit need to be modified connect
1. Merge branch 'develop' & fixed conflicts
2. Plus HTML & SCSS in pages: user_define, about
3. Modified Views: registrations#edit, devise/sessions#new, links.html.erb
4. Connect db information

### CODE REVIEW

**Comment by chaochaowu** [comment]
@dannyh79 sor, already modified

**Comment by dannyh79** [comment]
The web app has switched to Postgres. Kindly merge the lastest commit from "develop" into this branch. :)

**Comment by chaochaowu** [comment]
@dannyh79 The branch is already switched database to Postgres, and I also fixed one path. Plz check again, thx :D

**Comment by dannyh79** [comment]
@chaochaowu kindly check the commited changes. The layout of calc page is broken since commit# 610423a

**Comment by chaochaowu** [comment]
@dannyh79 already fixed it, kindly check it again, thx :)

**Pull request merged**
